
# C:\Users\Owner\Desktop\Programming\Math\MathLISP\tm.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '8932AA23CCFE185780440D722DC698B9'
    
_lr_action_items = {'STR':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[1,-6,-8,-4,1,-10,-7,1,-9,-5,-2,1,1,-1,]),'SPINT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[2,-6,-8,-4,2,-10,-7,2,-9,-5,-2,2,2,-1,]),'INT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[3,-6,-8,-4,3,-10,-7,3,-9,-5,-2,3,3,-1,]),'OPAREN':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[4,-6,-8,-4,4,-10,-7,4,-9,-5,-2,4,4,-1,]),'$end':([1,2,3,5,6,7,8,9,10,12,13,],[-6,-8,-4,-10,-7,0,-9,-5,-2,-3,-1,]),'BOOL':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[6,-6,-8,-4,6,-10,-7,6,-9,-5,-2,6,6,-1,]),'FUNC':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[5,-6,-8,-4,5,-10,-7,5,-9,-5,-2,5,5,-1,]),'CPAREN':([1,2,3,4,5,6,8,9,10,11,12,13,],[-6,-8,-4,10,-10,-7,-9,-5,-2,13,-3,-1,]),'SPFLOAT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[8,-6,-8,-4,8,-10,-7,8,-9,-5,-2,8,8,-1,]),'FLOAT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[9,-6,-8,-4,9,-10,-7,9,-9,-5,-2,9,9,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,7,11,12,],[7,11,12,12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> OPAREN expression CPAREN','expression',3,'p_expression_s','parse.py',14),
  ('expression -> OPAREN CPAREN','expression',2,'p_expression_empty','parse.py',20),
  ('expression -> expression expression','expression',2,'p_expression_list','parse.py',26),
  ('expression -> INT','expression',1,'p_expression_unit','parse.py',33),
  ('expression -> FLOAT','expression',1,'p_expression_unit','parse.py',34),
  ('expression -> STR','expression',1,'p_expression_unit','parse.py',35),
  ('expression -> BOOL','expression',1,'p_expression_unit','parse.py',36),
  ('expression -> SPINT','expression',1,'p_expression_unit','parse.py',37),
  ('expression -> SPFLOAT','expression',1,'p_expression_unit','parse.py',38),
  ('expression -> FUNC','expression',1,'p_expression_func','parse.py',45),
]
